{{- range .Values.cas }}
{{- if eq .type "server" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .org }}-ca-deployment
  labels:
    app: {{ .org }}-ca
    type: ca-server
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .org }}-ca
      type: ca-server
  template:
    metadata:
      labels:
        app: {{ .org }}-ca
        type: ca-server
    spec:
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ $.Values.persistence.existingClaim }}
      containers:
        - name: {{ .org }}-ca
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          env:
            - name: FABRIC_CA_HOME
              value: {{ $.Values.env.server.FABRIC_CA_HOME }}
            - name: FABRIC_CA_SERVER_CA_NAME
              value: {{ $.Values.env.server.FABRIC_CA_SERVER_CA_NAME }}
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: {{ $.Values.env.server.FABRIC_CA_SERVER_TLS_ENABLED }}
            - name: FABRIC_CA_SERVER_PORT
              value: {{ $.Values.env.server.FABRIC_CA_SERVER_PORT }}
          ports:
            - containerPort: 7054
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server
              name: persistent-storage
              subPath: files/fabric-ca-server/{{ .org }}
---
{{- end }}
{{- if eq .type "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .org }}-ca-client-deployment
  labels:
    app: {{ .org }}-ca-client
    type: ca-client
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .org }}-ca-client
      type: ca-client
  template:
    metadata:
      labels:
        app: {{ .org }}-ca-client
        type: ca-client
    spec:
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ $.Values.persistence.existingClaim }}
      containers:
        - name: {{ .org }}-ca-client
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          env:
            - name: FABRIC_CA_CLIENT_HOME
              value: {{ $.Values.env.client.FABRIC_CA_CLIENT_HOME }}
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-client
              name: persistent-storage
              subPath: files/fabric-ca-client/{{ .org }}
---
{{- end }}
{{- end }}