{{- range .Values.cas }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .org }}-ca-service
  labels:
    app: {{ .org }}-ca
spec:
  type: {{ $.Values.service.type }}
  selector:
    app: {{ .org }}-ca
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.port }}
---
{{- end }}