apiVersion: v1
kind: Service
metadata:
  name: couchdb-consumer
  labels:
    app: couchdb
    org: consumer
spec:
  type: ClusterIP
  ports:
    - port: 5984
      targetPort: 5984
  selector:
    app: couchdb
    org: consumer