apiVersion: v1
kind: Service
metadata:
  name: couchdb-qedadmin
  labels:
    app: couchdb
    org: qedadmin
spec:
  type: ClusterIP
  ports:
    - port: 5984
      targetPort: 5984
  selector:
    app: couchdb
    org: qedadmin