apiVersion: v1
kind: Service
metadata:
  name: cronjobs
  labels:
    app: cronjobs
spec:
  type: {{ .Values.cronjobService.type }}
  selector:
    app: cronjobs
  ports:
    - port: {{ .Values.cronjobService.port }}
      targetPort: {{ .Values.cronjobService.targetPort }}