cas:
  - org: customer
    type: server
  - org: customer
    type: client
  - org: manufacturer
    type: server
  - org: manufacturer
    type: client
  - org: orderers
    type: server
  - org: orderers
    type: client
  - org: qed-admin
    type: server
  - org: qed-admin
    type: client

replicaCount: 1

image:
  repository: hyperledger/fabric-ca
  tag: "1.5"

persistence:
  enabled: true
  existingClaim: efs-claim

service:
  type: ClusterIP
  port: 7054

env:
  server:
    FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
    FABRIC_CA_SERVER_CA_NAME: ca
    FABRIC_CA_SERVER_TLS_ENABLED: "true"
    FABRIC_CA_SERVER_PORT: "7054"
  client:
    FABRIC_CA_CLIENT_HOME: /etc/hyperledger/fabric-ca-client